library verilog;
use verilog.vl_types.all;
entity ID_EX is
    port(
        pc_i            : in     vl_logic_vector(31 downto 0);
        pc_o            : out    vl_logic_vector(31 downto 0);
        RegWrite_i      : in     vl_logic;
        RegWrite_o      : out    vl_logic;
        RegData_i       : in     vl_logic_vector(1 downto 0);
        RegData_o       : out    vl_logic_vector(1 downto 0);
        MemRead_i       : in     vl_logic;
        MemRead_o       : out    vl_logic;
        MemWrite_i      : in     vl_logic;
        MemWrite_o      : out    vl_logic;
        ALUSrcA_i       : in     vl_logic;
        ALUSrcA_o       : out    vl_logic;
        ALUSrcB_i       : in     vl_logic;
        ALUSrcB_o       : out    vl_logic;
        ALUOp_i         : in     vl_logic_vector(3 downto 0);
        ALUOp_o         : out    vl_logic_vector(3 downto 0);
        RegDst_i        : in     vl_logic;
        RegDst_o        : out    vl_logic;
        Op_i            : in     vl_logic_vector(5 downto 0);
        Op_o            : out    vl_logic_vector(5 downto 0);
        R1_i            : in     vl_logic_vector(31 downto 0);
        R1_o            : out    vl_logic_vector(31 downto 0);
        R2_i            : in     vl_logic_vector(31 downto 0);
        R2_o            : out    vl_logic_vector(31 downto 0);
        Shamt_i         : in     vl_logic_vector(4 downto 0);
        Shamt_o         : out    vl_logic_vector(4 downto 0);
        Imm_i           : in     vl_logic_vector(31 downto 0);
        Imm_o           : out    vl_logic_vector(31 downto 0);
        Funct_i         : in     vl_logic_vector(5 downto 0);
        Funct_o         : out    vl_logic_vector(5 downto 0);
        Rs_i            : in     vl_logic_vector(5 downto 0);
        Rs_o            : out    vl_logic_vector(5 downto 0);
        Rt_i            : in     vl_logic_vector(5 downto 0);
        Rt_o            : out    vl_logic_vector(5 downto 0);
        Rd_i            : in     vl_logic_vector(5 downto 0);
        Rd_o            : out    vl_logic_vector(5 downto 0);
        c0Data_i        : in     vl_logic_vector(31 downto 0);
        c0Data_o        : out    vl_logic_vector(31 downto 0);
        mfc0_i          : in     vl_logic;
        mfc0_o          : out    vl_logic;
        clk             : in     vl_logic;
        rst             : in     vl_logic;
        Cancel_ID       : in     vl_logic
    );
end ID_EX;
